---
title: "Final_Project_Work"
author: "David Liddle/Fiona Kelley"
date: "2023-11-25"
output: pdf_document
---

```{r setup, include=FALSE}

library(tidyverse);library(lubridate);library(here);library(ggplot2);
library(cowplot);library(knitr); library(agricolae);library(dplyr)
library(here)
```

```{r Set Theme}
#2 Build ggplot theme
salmon_theme <- theme_classic(base_size = 14) +
theme(axis.text = element_text(color = "black"),
legend.position = "right",
panel.grid.minor = element_line(color = "gray", linetype = "solid"),
panel.grid.major = element_line(color = "gray", linetype = "solid"),
legend.background = element_rect(fill = "gray"))
#Set the theme
theme_set(salmon_theme)
```

```{r Import Wrangled Data}
salmon_data <- read.csv(here("Data","Raw","salmon_data.csv"),
  stringsAsFactors = TRUE)
```

```{r Split Dataset by Species + Additional Wrangling}
#Add Month column to data for multiple regression analysis later
salmon_data$Month <- as.Date(month(salmon_data$SurveyDate))
#Split Dataset up by species
salmon_chin <- salmon_data %>% filter(SpeciesAbbr=="CHIN")
salmon_sock <- salmon_data %>% filter(SpeciesAbbr=="SOCK")
salmon_coho <- salmon_data %>% filter(SpeciesAbbr=="COHO")

#export separated species data 
write.csv(
  salmon_chin, row.names = FALSE, file = 
    "./Data/Processed/ChinookSalmon_ProcessedData.csv")
write.csv(
  salmon_coho, row.names = FALSE, file = 
    "./Data/Processed/CohoSalmon_ProcessedData.csv")
write.csv(
  salmon_sock, row.names = FALSE, file = 
    "./Data/Processed/SockeyeSalmon_ProcessedData.csv")
```

```{r Calculate and Graph Average Count Data}

Average_LiveCount <- salmon_data %>%
  group_by(SpeciesAbbr, RunYear) %>% # Group the data by Species and Run Year
  summarise(Avg_Live = mean(LiveTotal, na.rm = TRUE)) #find average live count

Average_DeadCount <- salmon_data %>%
  group_by(SpeciesAbbr, RunYear) %>% # Group the data by Species and Run Year
  summarise(Avg_Dead = mean(DeadTotal, na.rm = TRUE)) #Find average dead count

Average_CombinedRedd <- salmon_data %>%
  group_by(SpeciesAbbr, RunYear) %>% # Group the data by Species and Run Year
  summarise(Avg_CombinedRedd = mean(CombinedReddCount, na.rm = TRUE)) #find average combined redd count

Average_NewRedd <- salmon_data %>%
  group_by(SpeciesAbbr, RunYear) %>% # Group the data by Species and Run Year
  summarise(Avg_NewRedd = mean(NewReddCount, na.rm = TRUE)) #find average new redd count

ggplot(Average_LiveCount, aes(x = RunYear, y = Avg_Live, fill = SpeciesAbbr)) +
  geom_col(position = "dodge") +
  labs(title = "Average Live Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

ggplot(Average_DeadCount, aes(x = RunYear, y = Avg_Dead, fill = SpeciesAbbr)) +
  geom_col(position = "dodge") +
  labs(title = "Average Dead Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

ggplot(Average_CombinedRedd, aes(x = RunYear, y = Avg_CombinedRedd, fill = SpeciesAbbr)) +
  geom_col(position = "dodge") +
  labs(title = "Average Combined Redd Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

ggplot(Average_NewRedd, aes(x = RunYear, y = Avg_NewRedd, fill = SpeciesAbbr)) +
  geom_col(position = "dodge") +
  labs(title = "Average New Redd Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

```

```{r Calculate and Graph Average Counts by Species}
#Chinook counts
AverageLive_Chinook <- salmon_chin %>% 
  group_by(RunYear) %>% 
  summarise(Avg_Live = mean(LiveTotal, na.rm = TRUE))

ggplot(AverageLive_Chinook, aes(x = RunYear, y = Avg_Live)) +
  geom_col() +
  labs(title = "Average Live Chinook Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

AverageNewRedd_Chinook <- salmon_chin %>% 
  group_by(RunYear) %>% 
  summarise(Avg_NewRedd = mean(NewReddCount, na.rm = TRUE))

ggplot(AverageNewRedd_Chinook, aes(x = RunYear, y = Avg_NewRedd)) +
  geom_col() +
  labs(title = "Average New Redd Chinook Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

#Sockeye counts
AverageLive_Sockeye <- salmon_sock %>% 
  group_by(RunYear) %>% 
  summarise(Avg_Live = mean(LiveTotal, na.rm = TRUE))

ggplot(AverageLive_Sockeye, aes(x = RunYear, y = Avg_Live)) +
  geom_col() +
  labs(title = "Average Live Sockeye Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

AverageNewRedd_Sockeye <- salmon_sock %>% 
  group_by(RunYear) %>% 
  summarise(Avg_NewRedd = mean(NewReddCount, na.rm = TRUE))

ggplot(AverageNewRedd_Sockeye, aes(x = RunYear, y = Avg_NewRedd)) +
  geom_col() +
  labs(title = "Average New Redd Sockeye Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

#Coho counts 

AverageLive_Coho <- salmon_coho %>% 
  group_by(RunYear) %>% 
  summarise(Avg_Live = mean(LiveTotal, na.rm = TRUE))

ggplot(AverageLive_Coho, aes(x = RunYear, y = Avg_Live)) +
  geom_col() +
  labs(title = "Average Live Coho Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

AverageNewRedd_Coho <- salmon_coho %>% 
  group_by(RunYear) %>% 
  summarise(Avg_NewRedd = mean(NewReddCount, na.rm = TRUE))

ggplot(AverageNewRedd_Coho, aes(x = RunYear, y = Avg_NewRedd)) +
  geom_col() +
  labs(title = "Average New Redd Coho Salmon Count from 1973 to 2023",
       x = "Year", y = "Count")

#Total redd count bar graph. 
TotalReddPlot <- ggplot(salmon_data, aes(x = RunYear, y = CombinedReddCount, fill = Species)) +
  geom_bar(stat = "identity", width = 0.8) +
  labs(title = "Total Salmon Redds per Year",
       x = "Run Year",
       y = "Total Redd Count", 
       fill = "Salmon Species") +
  scale_y_continuous(labels = scales::comma_format(scale = 1e3)) 
TotalReddPlot
```

```{r Scatterplots by Species}
#Plot species counts. 
LiveSalmon_scatter <- 
  ggplot(salmon_data, aes(x=RunYear, y=LiveTotal, color = Species))+
  geom_point(size = 0.7) +
  labs(title = "Salmon Live Count Observations (1973 to 2023)", 
       x = "Year",
       y = "Salmon Count",
       color = "Salmon Species")
LiveSalmon_scatter

# Define lower and upper bounds for LiveTotal (Used ChatGPT to assist in removing outliers)
lower_bound_LiveTotal <- 0
upper_bound_LiveTotal <- 5000
# Filter data to remove outliers
CleanLiveSalmon_data <- salmon_data %>%
  filter(LiveTotal >= lower_bound_LiveTotal & LiveTotal <= upper_bound_LiveTotal)

# Plot live counts 
LiveSalmon_scatter <- ggplot(CleanLiveSalmon_data, aes(x = RunYear, y = LiveTotal, color = Species)) +
  geom_point(size = 0.7) +
  geom_smooth(method = "lm", se = FALSE)
  labs(
    title = "Salmon Live Count Observations without Outliers (1973 to 2023)",
    x = "Year",
    y = "Salmon Count",
    color = "Salmon Species"
  )

LiveSalmon_scatter

```

```{r Salmon Boxplots}

#Boxplot of total live salmon counts. 
LiveSalmon_boxplot <- ggplot(salmon_data, 
aes( x = RunYear, y = LiveTotal, color = Species)) +
geom_boxplot(na.rm = TRUE) + 
  #Found this function on ChatGPT, it put the months in correct order
   labs(title = "Salmon Populations from 1973 to 2023", #Create title and label axes
       x = "Year",
       y = "Salmon Live Count", color = "Species")
LiveSalmon_boxplot

Average_LiveCount <- salmon_data %>%
  group_by(SpeciesAbbr, RunYear) %>% # Group the data by Species and Run Year
  summarise(Avg_Live = mean(LiveTotal, na.rm = TRUE)) #find average live count

LiveSalmon_boxplot <- ggplot(Average_LiveCount, 
aes( x = RunYear, y = Avg_Live)) +
geom_boxplot(na.rm = TRUE) + 
  #Found this function on ChatGPT, it put the months in correct order
   labs(title = "Salmon Populations from 1973 to 2023", #Create title and label axes
       x = "Year",
       y = "Salmon Live Count", color = "Species")
LiveSalmon_boxplot
#Caption & Print 
caption_text <- "Figure 4: Live counts of salmon in Washington streams from 1973 to 2023."
LiveSalmonBoxplot_caption <- plot_grid(LiveSalmon_boxplot, 
                                      cowplot::draw_label(caption_text, size = 10), 
                                      ncol = 1, align = "v")
print(LiveSalmonBoxplot_caption)

#Boxplot of salmon redds.  
NewRedd_boxplot <- ggplot(salmon_data, 
aes( x = RunYear, y = NewReddCount, color = Species)) +
geom_boxplot(na.rm = TRUE) + 
  #Found this function on ChatGPT, it put the months in correct order
   labs(title = "New Salmon Redds Observed from 1973 to 2023", #Create title and label axes
       x = "Year",
       y = "Salmon Redds Count", color = "Species")
NewRedd_boxplot

```

```{r Average Annual Temperature}

#Calculate average water temperature. 
AverageAnnualTemp_salmon <- salmon_data %>%
  group_by(RunYear) %>% # Group the data by year
  summarise(Avg_WaterTemp = mean(WaterTempFarenheit, na.rm = TRUE))
ggplot(salmon_data, aes(x=SurveyDate, y=WaterTempFarenheit))+
  geom_point()

```

```{r Linear Regression for Salmon Counts and Temperature}
#For All Species
#Correlation between live counts and temperature
LiveCounts_Temp<- lm(data = salmon_data, LiveTotal ~ WaterTempFarenheit)
summary(LiveCounts_Temp)
plot(LiveCounts_Temp)
#Correlation between new redd counts and temperature
NewReddCounts_Temp<- lm(data = salmon_data, NewReddCount ~ WaterTempFarenheit)
summary(NewReddCounts_Temp)
plot(NewReddCounts_Temp)

#Sockeye Linear Regression
#Correlation between live counts and temperature

LiveCountssock_Temp<- lm(data = salmon_sock, LiveTotal ~ WaterTempFarenheit)
summary(LiveCountssock_Temp)
plot(LiveCountssock_Temp)

#Correlation between new redd counts and temperature

NewReddCountssock_Temp<- lm(data = salmon_sock, NewReddCount ~ WaterTempFarenheit)
summary(NewReddCountssock_Temp)
plot(NewReddCountssock_Temp)

#Chinook Linear Regression
#Correlation between live counts and temperature

LiveCountschin_Temp<- lm(data = salmon_chin, LiveTotal ~ WaterTempFarenheit)
summary(LiveCountschin_Temp)
plot(LiveCountschin_Temp)

#Correlation between new redd counts and temperature

NewReddCountschin_Temp<- lm(data = salmon_chin, NewReddCount ~ WaterTempFarenheit)
summary(NewReddCountschin_Temp)
plot(NewReddCountschin_Temp)

#Coho Linear Regression
#Correlation between live counts and temperature

LiveCountscoho_Temp<- lm(data = salmon_coho, LiveTotal ~ WaterTempFarenheit)
summary(LiveCountscoho_Temp)
plot(LiveCountscoho_Temp)

#Correlation between new redd counts and temperature

NewReddCountscoho_Temp<- lm(data = salmon_coho, NewReddCount ~ WaterTempFarenheit)
summary(NewReddCountscoho_Temp)
plot(NewReddCountscoho_Temp)
```

```{r Multiple Regression Analysis for Live Count}
# Create AIC to determine what set of variables is the live count predictor
TPAIC <- lm(data = salmon_data, LiveTotal ~ WaterTempFarenheit + Month)
step(TPAIC)
# Define the multiple regression model
model <- lm(data = salmon_data, LiveTotal ~ WaterTempFarenheit + Month)

# Fit the model
summary(model)
```

```{r Multiple Regression New Redd Counts}
# Create AIC to determine what set of variables is the live count predictor
TPAIC2 <- lm(data = salmon_data, NewReddCount ~ WaterTempFarenheit + Month)
step(TPAIC2)
# Define the multiple regression model
model2 <- lm(data = salmon_data, NewReddCount ~ WaterTempFarenheit + Month)

# Fit the model
summary(model)

#Because Sockeye New Redd was the only factor with not enough evidence to reject the null, this was because of a lack of temperature data for sockeye salmon
#Run Sockeye New Redd and Live Count Single Regression
#Redd Count
NewReddCountssock_month<- lm(data = salmon_sock, NewReddCount ~ Month)
summary(NewReddCountssock_month)
plot(NewReddCountssock_month)
#Live Count
LiveCountssock_month<- lm(data = salmon_sock, LiveTotal ~ Month)
summary(LiveCountssock_month)
plot(LiveCountssock_month)
```

```{r Time Series Analysis Interpolation & Data Preparation}
#Add linear interpolation to missing data Live Count
salmon_data_interpolated <- 
  salmon_data %>% 
  mutate(LiveTotal = zoo::na.approx(LiveTotal, SurveyDate))
#Create new data frame
salmon_data1 <- salmon_data_interpolated %>%
    mutate(Year = year(SurveyDate), Month = month(SurveyDate)) %>% #Ask about this in class
 group_by(Year, Month) %>%
# Calculate the mean live count for each month
  summarize(MeanLive = mean(LiveTotal)) %>%
# Create a new Date column with the first day of each month
  mutate(Date = ymd(paste(Year, Month, "01", sep = "-")))
# Arrange the data by Date if needed
salmon_data1 <- arrange(salmon_data1, Date)
# View the resulting data frame
head(salmon_data1)

#export interpolated data 
write.csv(
  salmon_data1, row.names = FALSE, file = "./Data/Processed/Salmon_ProcessedData_LiveCountInterpolation.csv")

#Add linear interpolation to missing data in New Redd Count
Redd_data_interpolated <- salmon_sock %>%
  mutate(
    NewReddCount = zoo::na.approx(NewReddCount, x = SurveyDate)
  )
# Create new data frame
redd_data_int <- Redd_data_interpolated%>%
    mutate(Year = year(SurveyDate), Month = month(SurveyDate)) %>%
 group_by(Year, Month) %>%
# Calculate the mean live and new redd count for each month
  summarize(MeanRedd = mean(NewReddCount)) %>%
# Create a new Date column with the first day of each month
  mutate(Date = ymd(paste(Year, Month, "01", sep = "-")))
# Arrange the data by Date if needed
redd_data_int <- arrange(redd_data_int, Date)
# View the resulting data frame
head(redd_data_int)
redd_data_int<- na.omit(redd_data_int)

#export interpolated data 
write.csv(
  redd_data_int, row.names = FALSE, file = "./Data/Processed/Salmon_ProcessedData_NewReddCountInterpolation.csv")

```


```{r Time Series Analysis}

#Generate time series for monthly average live counts 
f_month <- month(first(salmon_data1$Month))
f_year <- year(first(salmon_data1$Year))
salmonlive.monthly.ts <- ts(salmon_data1$MeanLive,
                   start=c(f_year,f_month),
                   frequency=12)
# Decompose monthly time series
salmon_data_decomp <- stl(salmonlive.monthly.ts, s.window = "periodic")
plot(salmon_data_decomp)
# Run SMK test
salmon_data_trend <- Kendall::SeasonalMannKendall(salmonlive.monthly.ts)
# Inspect results
salmon_data_trend
summary(salmon_data_trend)

#Generate time series for monthly average new redd counts 
f_month <- month(first(redd_data_int$Month))
f_year <- year(first(redd_data_int$Year))
salmonredd.monthly.ts <- ts(redd_data_int$MeanRedd,
                   start=c(f_year,f_month),
                   frequency=12)
# Decompose monthly time series
redd_data_decomp <- stl(salmonredd.monthly.ts, s.window = "periodic")
plot(redd_data_decomp)
# Run SMK test
redd_data_trend <- Kendall::SeasonalMannKendall(salmonredd.monthly.ts)
# Inspect results
redd_data_trend
summary(redd_data_trend)

```

```{r Time Series Analysis Interpolation & Data Preparation for Salmon Species}

# Add linear interpolation to missing data Chinook Live Count
chin_data_interpolated <- salmon_chin %>% 
  mutate(LiveTotal = zoo::na.approx(LiveTotal, SurveyDate)) %>% 
  mutate(NewReddCount = zoo::na.approx(NewReddCount, SurveyDate))
# Create new data frame
chin_data_int <- chin_data_interpolated%>%
    mutate(Year = year(SurveyDate), Month = month(SurveyDate)) %>%
 group_by(Year, Month) %>%
# Calculate the mean live and new redd count for each month
  summarize(MeanLive = mean(LiveTotal), MeanRedd = mean(NewReddCount)) %>%
# Create a new Date column with the first day of each month
  mutate(Date = ymd(paste(Year, Month, "01", sep = "-")))
# Arrange the data by Date if needed
chin_data_int <- arrange(chin_data_int, Date)
# View the resulting data frame
head(chin_data_int)
chin_data_int<- na.omit(chin_data_int)

# Add linear interpolation to missing data Coho live count 
coho_data_interpolated <- salmon_coho %>% 
  mutate(LiveTotal = zoo::na.approx(LiveTotal, xout = SurveyDate)) %>% 
  mutate(NewReddCount = zoo::na.approx(NewReddCount, xout = SurveyDate))
# Create new data frame
coho_data_int <- coho_data_interpolated%>%
    mutate(Year = year(SurveyDate), Month = month(SurveyDate)) %>%
 group_by(Year, Month) %>%
# Calculate the mean live and new redd count for each month
  summarize(MeanLive = mean(LiveTotal), MeanRedd = mean(NewReddCount)) %>%
# Create a new Date column with the first day of each month
  mutate(Date = ymd(paste(Year, Month, "01", sep = "-")))
# Arrange the data by Date if needed
coho_data_int <- arrange(coho_data_int, Date)
# View the resulting data frame
head(coho_data_int)

# Add linear interpolation to missing data Sockeye live count 
sock_data_interpolated <- salmon_sock %>%
  mutate(
    LiveTotal = zoo::na.approx(LiveTotal, x = SurveyDate),
    NewReddCount = zoo::na.approx(NewReddCount, x = SurveyDate)
  )

# Create new data frame
sock_data_int <- sock_data_interpolated%>%
    mutate(Year = year(SurveyDate), Month = month(SurveyDate)) %>%
 group_by(Year, Month) %>%
# Calculate the mean live and new redd count for each month
  summarize(MeanLive = mean(LiveTotal), MeanRedd = mean(NewReddCount)) %>%
# Create a new Date column with the first day of each month
  mutate(Date = ymd(paste(Year, Month, "01", sep = "-")))
# Arrange the data by Date if needed
sock_data_int <- arrange(sock_data_int, Date)
# View the resulting data frame
head(sock_data_int)
sock_data_int<- na.omit(sock_data_int)

#export interpolated data 
write.csv(
  chin_data_int, row.names = FALSE, file = 
    "./Data/Processed/ChinookSalmon_ProcessedData_Interpolation.csv")
write.csv(
  coho_data_int, row.names = FALSE, file = 
    "./Data/Processed/CohoSalmon_ProcessedData_Interpolation.csv")
write.csv(
  sock_data_int, row.names = FALSE, file = 
    "./Data/Processed/SockeyeSalmon_ProcessedData_Interpolation.csv")

```

```{r Species Time Series Analysis}

# Generate time series for Chinook monthly average live counts 
f_month <- month(first(chin_data_int$Month))
f_year <- year(first(chin_data_int$Year))
chin_live.monthly.ts <- ts(chin_data_int$MeanLive,
                   start=c(f_year,f_month),
                   frequency=12)
# Decompose monthly time series
chin_data_decomp <- stl(chin_live.monthly.ts, s.window = "periodic")
plot(chin_data_decomp)
# Run SMK test
chin_live_data_trend <- Kendall::SeasonalMannKendall(chin_live.monthly.ts)
# Inspect results
chin_live_data_trend
summary(chin_live_data_trend)

# Generate time series for Chinook monthly average redd counts 
f_month <- month(first(chin_data_int$Month))
f_year <- year(first(chin_data_int$Year))
chin_redd.monthly.ts <- ts(chin_data_int$MeanRedd,
                   start=c(f_year,f_month),
                   frequency=12)
# Decompose monthly time series
chin_redd_data_decomp <- stl(chin_redd.monthly.ts, s.window = "periodic")
plot(chin_redd_data_decomp)
# Run SMK test
chin_redd_data_trend <- Kendall::SeasonalMannKendall(chin_redd.monthly.ts)
# Inspect results
chin_redd_data_trend
summary(chin_redd_data_trend)

# Generate time series for Coho monthly average live counts 
f_month <- month(first(coho_data_int$Month))
f_year <- year(first(coho_data_int$Year))
coho_live.monthly.ts <- ts(coho_data_int$MeanLive,
                   start=c(f_year,f_month),
                   frequency=12)
# Decompose monthly time series
coho_data_decomp <- stl(coho_live.monthly.ts, s.window = "periodic")
plot(coho_data_decomp)
# Run SMK test
coho_live_data_trend <- Kendall::SeasonalMannKendall(coho_live.monthly.ts)
# Inspect results
coho_live_data_trend
summary(coho_live_data_trend)

# Generate time series for Coho monthly average redd counts 
f_month <- month(first(coho_data_int$Month))
f_year <- year(first(coho_data_int$Year))
coho_redd.monthly.ts <- ts(coho_data_int$MeanRedd,
                   start=c(f_year,f_month),
                   frequency=12)
# Decompose monthly time series
coho_redd_data_decomp <- stl(coho_redd.monthly.ts, s.window = "periodic")
plot(coho_redd_data_decomp)
# Run SMK test
coho_redd_data_trend <- Kendall::SeasonalMannKendall(coho_redd.monthly.ts)
# Inspect results
coho_redd_data_trend
summary(coho_redd_data_trend)

# Generate time series for Sockeye monthly average live counts 
f_month <- month(first(sock_data_int$Month))
f_year <- year(first(sock_data_int$Year))
sock_live.monthly.ts <- ts(sock_data_int$MeanLive,
                   start=c(f_year,f_month),
                   frequency=12)
# Decompose monthly time series
sock_data_decomp <- stl(sock_live.monthly.ts, s.window = "periodic")
plot(sock_data_decomp)
# Run SMK test
sock_live_data_trend <- Kendall::SeasonalMannKendall(sock_live.monthly.ts)
# Inspect results
sock_live_data_trend
summary(sock_live_data_trend)

# Generate time series for Sockeye monthly average redd counts 
f_month <- month(first(sock_data_int$Month))
f_year <- year(first(sock_data_int$Year))
sock_redd.monthly.ts <- ts(sock_data_int$MeanRedd,
                   start=c(f_year,f_month),
                   frequency=12)
# Decompose monthly time series
sock_redd_data_decomp <- stl(sock_redd.monthly.ts, s.window = "periodic")
plot(sock_redd_data_decomp)
# Run SMK test
sock_redd_data_trend <- Kendall::SeasonalMannKendall(sock_redd.monthly.ts)
# Inspect results
sock_redd_data_trend
summary(sock_redd_data_trend)
```

```{r Graph Average }
# Calculate mean, minimum, and maximum values by grouping variable x
# Extract Year and Month from SurveyDate
salmon_chin1 <- salmon_chin %>%
  mutate(Year = year(SurveyDate),
         Month = month(SurveyDate))

# Group by Year and Month, calculate the average live count
average_live_chin <- salmon_chin1 %>%
  group_by(Year, Month) %>%
  summarise(Avg_Live = mean(LiveTotal, na.rm = TRUE), Minimum = min(LiveTotal, na.rm=TRUE), Maximum = max(LiveTotal, na.rm = TRUE))

# Create a line graph with shades around the line
ggplot(average_live_chin, aes(x = Month, y = Avg_Live)) +
  geom_line(color = "blue") +
  geom_ribbon(aes(ymin = Minimum, ymax = Maximum), fill = "blue", alpha = 0.3) +
  labs(
    title = "Line Graph with Shaded Area",
    x = "X-axis Label",
    y = "Y-axis Label"
  )

```

```{r Organize data by Observation Year}
#Sorting for Chinook
# Live Salmon Counts
salmon_chin_live <- salmon_chin %>%
  group_by(RunYear) %>%
  summarize(average_live = mean(LiveTotal))
# Dead Salmon Counts
salmon_chin_dead <- salmon_chin %>%
  group_by(RunYear) %>%
  summarize(average_dead = mean(DeadTotal))
#Merge datasets
Combined_chin <- full_join(salmon_chin_live, salmon_chin_dead)

#Sorting for Sockeye
# Live Salmon Counts
salmon_sock_live <- salmon_sock %>%
  group_by(RunYear) %>%
  summarize(average_live = mean(LiveTotal))
# Dead Salmon Counts
salmon_sock_dead <- salmon_sock %>%
  group_by(RunYear) %>%
  summarize(average_dead = mean(DeadTotal))
#Merge datasets
Combined_sock <- full_join(salmon_sock_live, salmon_sock_dead)

#Sorting for Coho
# Live Salmon Counts
salmon_coho_live <- salmon_coho %>%
  group_by(RunYear) %>%
  summarize(average_live = mean(LiveTotal))
# Dead Salmon Counts
salmon_coho_dead <- salmon_coho %>%
  group_by(RunYear) %>%
  summarize(average_dead = mean(DeadTotal))
#Merge datasets
Combined_coho <- full_join(salmon_coho_live, salmon_coho_dead)

```

```{r Data Reshaping}
#Reshape Data
salmon_chin_long <- gather(Combined_chin, key = "status", value = "count", -RunYear)
salmon_sock_long <- gather(Combined_sock, key = "status", value = "count", -RunYear)
salmon_coho_long <- gather(Combined_coho, key = "status", value = "count", -RunYear)
```

```{r Graphing the Data}
#Plot Chinook Data
ggplot(salmon_chin_long,aes(x=RunYear,y=count, color=status)) + 
  geom_line() +
  labs(title ="Average Live and Dead Chinook Salmon Counts",
       x = "Year",y = "Count", color="Status") +
  scale_color_manual(
    values = c("average_live" = "blue", "average_dead" = "red"),
    labels = c("Dead Count", "Live Count"))
#Plot Sockeye Data
ggplot(salmon_sock_long,aes(x=RunYear,y=count, color=status)) + 
  geom_line() +
  labs(title ="Average Live and Dead Sockeye Salmon Counts",
       x = "Year",y = "Count", color="Status") +
  scale_color_manual(
    values = c("average_live" = "blue", "average_dead" = "red"),
    labels = c("Dead Count", "Live Count"))
#Plot Coho Data
ggplot(salmon_coho_long,aes(x=RunYear,y=count, color=status)) + 
  geom_line() +
  labs(title ="Average Live and Dead Coho Salmon Counts",
       x = "Year",y = "Count", color="Status") +
  scale_color_manual(
    values = c("average_live" = "blue", "average_dead" = "red"),
    labels = c("Dead Count", "Live Count"))

salmon_data_WRIA <- salmon_data_species %>% filter(WRIA %in% c(17,18,19))

ggplot(salmon_data_WRIA, aes(x = RunYear, y = LiveTotal)) +
  geom_point() +
  geom_smooth(method = 'loess', se = FALSE, color="green") +
  labs(title = "Chinook/Coho/Sockeye Salmon Live Counts in Study Area",
       x = "Year", y = "Live Count")
```

```{r Graphing the Data}
#Plot Chinook Data
ggplot(salmon_chin_long,aes(x=RunYear,y=count, color=status)) + 
   geom_point() +
  geom_smooth(method = 'loess', se = FALSE, color="black") +
  labs(title ="Average Live and Dead Chinook Salmon Counts",
       x = "Year",y = "Count", color="Status") +
  scale_color_manual(
    values = c("average_live" = "blue", "average_dead" = "red"),
    labels = c("Dead Count", "Live Count"))
#Plot Sockeye Data
ggplot(salmon_sock_long,aes(x=RunYear,y=count, color=status)) + 
  geom_point() +
  geom_smooth(method = 'loess', se = FALSE, color="black") +
  labs(title ="Average Live and Dead Sockeye Salmon Counts",
       x = "Year",y = "Count", color="Status") +
  scale_color_manual(
    values = c("average_live" = "blue", "average_dead" = "red"),
    labels = c("Dead Count", "Live Count"))
#Plot Coho Data
ggplot(salmon_coho_long,aes(x=RunYear,y=count, color=status)) + 
  geom_point() +
  geom_smooth(method = 'loess', se = FALSE, color="black") +
  labs(title ="Average Live and Dead Coho Salmon Counts",
       x = "Year",y = "Count", color="Status") +
  scale_color_manual(
    values = c("average_live" = "blue", "average_dead" = "red"),
    labels = c("Dead Count", "Live Count"))
```

```{r Temperature Data}
# Temperatures
salmon_data_temp <- salmon_data_species%>%
  select(RunYear,WaterTempFarenheit) %>% na.omit()
# Average Temperatures
salmon_data_temp_avg <- salmon_data_temp%>%
  group_by(RunYear) %>%
  summarize(avg.temp = mean(WaterTempFarenheit))
```

```{r Map of Streams}
install.packages("sf")
library(sf)

data <- st_read(here('Washington_Streams.gdb'))
library(mapview)
mapView(data)

```


