---
title: "EDA_FinalProject"
author: "Fiona Kelley & David Liddle"
date: "2023-11-25"
output: pdf_document
---

```{r setup, include=FALSE}

library(tidyverse);library(lubridate);library(here);library(ggplot2);
library(cowplot);library(knitr); library(agricolae);library(dplyr)
library(here)

getwd()

```

```{r Loading & Wrangling Data}
salmon_data <- read.csv(here("Data","Raw","WDFW-SGS_20231022.csv"),
  stringsAsFactors = TRUE)%>% 
  mutate(SurveyDate = mdy(SurveyDate))%>% #Turn survey dates into a date factor
  filter(RunYear>=1973, SpeciesAbbr %in% c("CHIN","COHO","SOCK")) %>% 
  #Include only last 50 years of data, and species of interest
  select(c("SurveyID","SurveyDate","WRIA","StreamCatalogCode","StreamName",
           "WaterTempFarenheit","SpeciesAbbr","Species","RunYear","LiveTotal",
           "DeadTotal","NewReddCount","PreviousReddCount",
           "CombinedReddCount"))#Keep columns of interest
```

```{r Write into a CSV file}
#6 Saving the wrangled dataset as a csv file. 
write.csv(
  salmon_data, row.names = FALSE, file = "./Data/Raw/salmon_data.csv")
```

